import numpy as np
from pandas import DataFrame
from sklearn.base import TransformerMixin
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.preprocessing import (
    Binarizer,
    FunctionTransformer,
    Normalizer,
    StandardScaler,
)
from skbio.stats.composition import multi_replace
from optuna.trial import FixedTrial, Trial
from typing import Protocol


class BaseScalerStrategy(Protocol):
    def create_scaler(self, trial: Trial | FixedTrial) -> TransformerMixin | Pipeline:
        return TransformerMixin()


def clr_transform(X: np.ndarray | DataFrame) -> np.ndarray | DataFrame:
    """
    Implements the Centered Log Ratio transform, which is recommended for
    dealing with compositional data as such generated by High Throughput
    Sequencing
    """
    # Need to make sure X is at least 2d to not have problems with LeaveOneOut
    X_zeroless = multi_replace(np.asarray(X))
    X_2d = np.atleast_2d(X_zeroless)

    log_X = np.log(X_2d)
    geo_mean = log_X.mean(axis=1, keepdims=True)

    return log_X - geo_mean


class CLRTransformer:
    def create_scaler(self, trial: Trial | FixedTrial) -> TransformerMixin:
        return FunctionTransformer(clr_transform)


class PassthroughScaler:
    def create_scaler(self, trial: Trial | FixedTrial) -> TransformerMixin:
        return FunctionTransformer(func=None)


class BinarizerScaler:
    def create_scaler(self, trial: Trial | FixedTrial) -> Pipeline:
        scaler_threshold = trial.suggest_float(
            "scaler_threshold", 0.00001, 0.005, log=True
        )
        normalizer = Normalizer(norm="l1")
        binarizer = Binarizer(threshold=scaler_threshold)
        scaler = make_pipeline(normalizer, binarizer)

        return scaler


class RelativeAbundanceScaler:
    def create_scaler(self, trial: Trial | FixedTrial) -> TransformerMixin:
        return Normalizer(norm="l1")


class Standardizer:
    def create_scaler(self, trial: Trial | FixedTrial) -> TransformerMixin:
        return StandardScaler()
