import numpy as np
from pandas import DataFrame
from sklearn.base import TransformerMixin
from sklearn.preprocessing import FunctionTransformer
from skbio.stats.composition import multi_replace
from optuna.trial import Trial
from typing import Protocol


class BaseScalerStrategy(Protocol):
    def create_scaler(self, trial: Trial) -> TransformerMixin:
        return TransformerMixin()


def clr_transform(X: np.ndarray | DataFrame) -> np.ndarray | DataFrame:
    """
    Implements the Centered Log Ratio transform, which is recommended for
    dealing with compositional data as such generated by High Throughput
    Sequencing
    """
    x_zeroless = multi_replace(np.asarray(X))

    log_X = np.log(x_zeroless)
    geo_mean = log_X.mean(axis=1, keepdims=True)

    return log_X - geo_mean


class CLRTransformer:
    def create_scaler(self, trial: Trial):
        return FunctionTransformer(clr_transform)
